In [ ]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

Hacemos un dataset artificial con la función `make_classification`

In [ ]:
features, target = make_classification(n_samples = 2000,
                                       n_features = 5,
                                       n_informative = 4,
                                       n_redundant = 1,
                                       n_classes = 2,
                                       weights = [.2, .8])

In [ ]:
print(features)

[[-2.21371097 -0.16305271  0.58993712  2.49133699 -2.02580861]
 [-1.42869249 -1.18620676  0.36907573  1.15333175 -0.87017412]
 [-1.32986085 -1.26264199  0.63286688  0.97949846 -0.84647247]
 ...
 [-2.92710185  0.54391803  0.28239492  0.57685746  1.99734646]
 [-0.66015443 -1.64600375  0.63452488  0.1333379  -0.28908813]
 [ 0.09786558 -0.83038695  1.23656005 -0.15848842 -0.67160215]]


In [ ]:
print(target)

[1 1 1 ... 1 1 1]


Pasamos las características y el target desde la listas a un dataframe, respectivamente,

In [ ]:
df_features = pd.DataFrame(features, columns=["Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5"])

In [ ]:
df_features.head()

Feature 1  Feature 2  Feature 3  Feature 4  Feature 5
0  -2.213711  -0.163053   0.589937   2.491337  -2.025809
1  -1.428692  -1.186207   0.369076   1.153332  -0.870174
2  -1.329861  -1.262642   0.632867   0.979498  -0.846472
3  -1.709873  -0.484190   0.028997   1.907287  -1.419901
4  -1.263076   3.294151  -0.372392   0.473612   1.539252

In [ ]:
df_target = pd.DataFrame(target, columns=["Target"])

In [ ]:
df_target.head()

Target
0       1
1       1
2       1
3       1
4       1

### Actividad 1


In [ ]:
df_target.iloc[:10,:]

Target
0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       0

El fin de esta actividad es medir el impacto del tamaño del conjunto de datos en el dataset. Para esto, vamos entrenar el modelo variando la entrada de los datos.

In [ ]:
results = []
for x in <codigo>: # to-do: hacer que x vaya en iteraciones de 50 en 50, a partir de 100., hasta 2000 i.e, 100,150,200,...
   clf = LogisticRegression(random_state=0).fit(df_features.iloc[:x,:], df_target.iloc[:x,:])
   # to-do: añadir el score del clasificador a la lista results
   results.append(<codigo>)

Graficar 

In [ ]:
# to-do: graficar - score vs tamaño del conjunto de datos